framework:
    mailer:
        dsn: 'null://null'
        envelope:
            sender: '%env(MAILER_FROM_EMAIL)%'
        headers:
            From: '%env(MAILER_FROM_NAME)% <%env(MAILER_FROM_EMAIL)%>'
