test: 
  tags:
    - php8.3
    - composer
  script: 
    - composer install
    - php bin/console sass:build
    - composer test
  artifacts:
    when: on_failure
    paths:
      - tests/_output/
    exclude:
      - tests/_output/.gitignore
